num_episodes: 10000
env: Taxi-v3
seed: 5
agent:
  type: montecarlo
  montecarlo:
    eps: 0.8
    decay_factor: 0.995
  sarsa:
    eps: 0.3
    decay_factor: 0.99
  qlearning:
    eps: 0.3
    decay_factor: 0.99