num_episodes: 500
env: Taxi-v3
agent:
  type: montecarlo
  montecarlo:
    eps: 0.5
    decay_factor: 0.99
  sarsa:
    eps: 0.3
    decay_factor: 0.99
  qlearning:
    eps: 0.3
    decay_factor: 0.99