num_episodes: 50
env: MountainCar-v0 # Taxi-v3, MountainCar-v0, SimpleLinear-v0
seed: 5
agent:
  type: qlearning # montecarlo, qlearning, sarsa
  montecarlo:
    eps: 0.8
    decay_factor: 0.995
  sarsa:
    eps: 0.8
    decay_factor: 0.999
    lr: 0.3
    gamma: 0.99
  qlearning:
    eps: 0.4
    decay_factor: 0.999
    lr: 0.4
    gamma: 0.95